## configuration
# Site
title: kdevkr github page
subtitle:
description:
author: kdevkr
language: ko
timezone: UTC

# URL
url: http://kdevkr.github.io
root: /
permalink: :year/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
archive_dir: archives
category_dir: categories
i18n_dir: :lang
tag_dir: tags
skip_render: [README.md]

# Writing
default_layout: post
titlecase: true
post_asset_folder: true
highlight:
  theme: github-gist

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
date_format: YYYY-MM-DD
time_format: H:mm:ss

# Pagination
per_page: 10
pagination_dir: page

# Extendsions
theme: snorlax
deploy:
  type: git
  repo: https://github.com/kdevkr/kdevkr.github.io.git
  branch: gh-pages
menu:
  Home: /
  Archives: /archives
  Categories: /categories
  About: /about

## plugins
index_generator:
  path: ''
  per_page: 10
  order_by: -date

category_generator:
  per_page: 10

archive_generator:
  per_page: 10
  yearly: true
  monthly: true
  daily: false
  order_by: -date
