## configuration

# Site
title:                           잠만보의 개발 블로그
subtitle:                        잠만보가 알려주는 개발 이야기
author:                          kdevkr
description:
language:                        ko
timezone:                        UTC

# URL
url:                             https://kdevkr.github.io
root:                            /
permalink:                       archives/:title/
permalink_defaults:

# Directory
source_dir:                      source
public_dir:                      public
archive_dir:                     archives
category_dir:                    categories
i18n_dir:                        :lang
tag_dir:                         tags
skip_render:                     [README.md, tmp/**]

# Writing
default_layout:                  post
render_drafts:                   false
titlecase:                       true
external_link:                   true
post_asset_folder:               true
future:                          false

# Category & Tag
default_category:                uncategorized
category_map:
tag_map:

# Date / Time format
date_format:                     YYYY-MM-DD
time_format:                     H:mm:ss

# Pagination
per_page:                        10
pagination_dir:                  page
    
deploy:
  type:                          git
  repo:                          https://__GITHUB_TOKEN__@github.com/kdevkr/kdevkr.github.io.git
  branch:                        master

google_site_verification:        googled619795c447b2a1d
naver_site_verification:         967670e7891eb52e115709ce4890e2e8f576a1e5

article_emoji:
  full:                          true

browsersync:
  ui:                            false

# https://futurecreator.github.io/2016/06/23/search-engine-optimization-hexo-plugins/
nofollow:
  enable:                        true

sitemap:
  path:                          sitemap.xml
  tag:                           false
  category:                      false
  
markdown: 'default'

highlight:
    line_number: false
    wrap: true
  
theme:                           next
theme_config:
    scheme:                      Gemini
    
    menu:
      home: / || home
      archives: /archives/ || archive
      개발:
          default: /development/ || dev fab
          일기장:
              default: /diary/ || newspaper
              이슈: /issue || exclamation-circle
          코드:
              default: /code || code
              Java: /java || java fab
              Spring: /spring || seedling
              Vue.js: /vuejs || vuejs fab
              PostgreSQL: /postgresql || database
              # 파이썬: /python || python fab
          # 운영체제:
          #     default: /os || desktop
          #     윈도우즈: /windows || windows fab
          #     리눅스: /ubuntu || linux fab
          #     맥: /mac || apple fab
          데브옵스: 
              default: /dev-ops || connectdevelop fab
              # 터미널: /terminal || terminal
              Jenkins: /jenkins || jenkins fab
              Docker: /docker || docker fab
              # 쿠버네티스: /kubernetes || none
          북마크:
              default: /bookmark/ || bookmark
              자바: /java || java fab
              스프링: /spring || seedling
              자바스크립트: /javascript || js-square fab
              데이터베이스: /database || database
              데브옵스: /dev-ops || connectdevelop fab
              도구: /tool || tools
              리뷰: /review || retweet
      소개: /about/ || user
              
    menu_settings:
        icons: true
        badges: true
      
    font:
      # Use custom fonts families or not.
      # Depended options:        `external` and `family`.
      enable:                    true

      # Uri of fonts host, e.g. //fonts.googleapis.com (Default).
      host:                      //fonts.googleapis.com

      # Font options:
      # `external:               true` will load this font family from `host` above.
      # `family:                 Times New Roman`. Without any quotes.
      # `size: x.x`. Use `em` as unit. Default: 1 (16px)

      # Global font settings used for all elements inside <body>.
      global:
        external:                true
        family:                  Arita Dotum
        size:                    1

      # Font settings for site title (.site-title).
      title:
        external:                true
        family:                  Mapo Peace Full
        size:                    1.25

      # Font settings for headlines (<h1> to <h6>).
      headings:
        external:                true
        family:                  Arita Dotum

      # Font settings for posts (.post-body).
      posts:
        external:                true
        family:                  Noto Serif KR

      # Font settings for <code> and code blocks.
      codes:
        external:                false
        family:                  Jetbrains Mono
    
    avatar:
        url:                     https://avatars1.githubusercontent.com/u/17937604?s=460&v=4
        rounded:                 true
        rotated:                 false
        
    pace:
        enable:                  true
        theme:                   center-atom
        
    excerpt:
      depth: 10
      excerpt_excludes: []
      more_excludes: []
      hideWholePostExcerpts: true
    
    pjax:                        true
    
    creative_commons:
      license:                   by-nc-sa
      sidebar:                   true
      post:                      false
      language:                  deed.ko
      
    safari_rainbow:              true
    
    custom_scrollbar:            true
    
    site_state:                  true
    
    social:
        GitHub:                  https://github.com/kdevkr || github fab
        E-Mail:                  mailto:kdevkr@gmail.com || envelope
        
    social_icons:
      enable:                    true
      icons_only:                false
      transition:                false
        
    motion:
        enable:                  false
        
    toc:
        enable:                  true
        number:                  true
        wrap:                    true
    
    sidebar:
        display:                 always
        scrollpercent:           true
        b2t:                     true
        
    back2top:
        enable:                  true
        sidebar:                 true
        scrollpercent:           true
        
    post_copyright:
        enable:                  true
        
    title_change:
      enable:                    false
      onmobile:                  false
      random:                    false
      timeout:                   2019
      hidden:
        favicon:                 /images/favicon-32x32-next.png
        title:
          #- 404
          #- φ(*￣0￣)
          #- Waiting for you.
      visible:
        favicon:                 /images/favicon-32x32-next.png
        title:
          #- 200
          #- (✿◡‿◡)
          #- Welcome back!
    # hexo-theme-next-anchor
    anchor:
      enable:                    true
      color:                     '#0e83cd'
      position:                  right # If left, anchors will always be visible.
      margin:                    7px 
      text:                      '#'
      icon:
        # If true, the `text` option will be ignored.
        enable:                  false 
        # By default, NexT has built-in FontAwesome support.
        # This option means `font-family: FontAwesome`, so DO Not change it.
        # Also you can choose ForkAwesome, but that's another story.
        font:                    FontAwesome
        content:                 \f0c1 # CSS content for FontAwesome & ForkAwesome.
        
    filter_optimize:
      enable:                    true
      # remove static resource query string
      #   - like `?v=1.0.0`
      remove_query_string:       true
      # remove the surrounding comments in each of the bundled files
      remove_comments:           false
      css:
        enable:                  true
        # bundle loaded css file into the one
        bundle:                  true
        # use a script block to load css elements dynamically
        delivery:                true
        # make specific css content inline into the html page
        #   - only support the full path
        #   - default is ['css/main.css']
        inlines:
        excludes:
      js:
        # bundle loaded js file into the one
        bundle:                  true
        excludes:
      # set the priority of this plugin,
      # lower means it will be executed first, default is 10
      priority:                  12
        
    symbols_count_time:
      symbols:                   true
      time:                      true
      total_symbols:             true
      total_time:                true
      exclude_codeblock:         true
      
    codeblock:
        # Code Highlight theme
        # Available values:      normal | night | night eighties | night blue | night bright | solarized | solarized dark | galactic
        # See:                   https://github.com/chriskempson/tomorrow-theme
      highlight_theme:         normal
        # Add copy button on codeblock
      copy_button:
        enable:                true
        # Show text copy result.
        show_result:           true
        # Available values:    default | flat | mac
        style:                 mac
        
    githubEmojis:
      enable:                    true
      className:                 github-emoji
      inject:                    true
          
    github_banner:
      enable:                    true
      permalink:                 https://github.com/kdevkr
      title:                     Follow me on GitHub
      
    reading_progress:
      enable:                  true
      color:                   "#37c6c0"
      height:                  5px
      
    disqusjs:
      enable:                    true
      api: https://disqus.com/api/
      apikey: CDGCVo6KP89BegKLv9vN5e8tZGWVf6TeHLWtkIz4ueXChOlkwAlacaYR5YNrY3Wi
      shortname: kdevkr-github-io
      
    fancybox: true
      
    # A JavaScript library for zooming images like Medium.
    mediumzoom:                  true
    
    # Vanilla JavaScript plugin for lazyloading images.
    lazyload:                    true
    
    google_analytics:            
      tracking_id:               UA-93954323-1
      localhost_ignored:         true
      
    busuanzi_count:
        enable:                  true
        total_visitors:          true
        total_visitors_icon:     user
        total_views:             true
        total_views_icon:        user
        post_views:              true
        post_views_icon:         user
        
    index_generator:
      path:                      ''
      per_page:                  10
      order_by:                  -date
    
    category_generator:
      per_page:                  10
    
    archive_generator:
      per_page:                  10
      yearly:                    true
      monthly:                   true
      daily:                     false
      order_by:                  -date
      
    tag_generator:
      per_page: 10
      order_by: -date
      
    # Allow to cache content generation. Introduced in NexT v6.0.0.
    cache:
      enable:                    false
          
    # Remove unnecessary files after hexo generate.
    minify:                      true
    
    note:
        style: flat
        icons: true
        
    exif:
      enable: true
      tags:
        FocalLength: "{value}mm"
        FNumber: "f/{value}"
        ExposureTime: "{value}s"
        
    bookmark:
      enable: false
      # Customize the color of the bookmark.
      color: "#222"
      # If auto, save the reading progress when closing the page or clicking the bookmark-icon.
      # If manual, only save it by clicking the bookmark-icon.
      save: auto
    
    disable_baidu_transformation: true
    canonical: true
    seo: true
        
    vendors:
        pjax: //cdn.jsdelivr.net/gh/theme-next/theme-next-pjax@0/pjax.min.js
        pace: //cdn.jsdelivr.net/npm/pace-js@1/pace.min.js
        pace_css: //cdn.jsdelivr.net/npm/pace-js@1/themes/blue/pace-theme-minimal.css
        
        # Internal version: 4.7.0
        # fontawesome: //cdn.jsdelivr.net/npm/font-awesome@4/css/font-awesome.min.css
        # fontawesome: //cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css
        fontawesome: https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/all.min.css
        
    # Custom Settings
    custom_file_path:
        #head:                   source/_data/head.swig
        #header:                 source/_data/header.swig
        #sidebar:                source/_data/sidebar.swig
        #postMeta:               source/_data/post-meta.swig
        #postBodyEnd:            source/_data/post-body-end.swig
        #footer:                 source/_data/footer.swig
        #bodyEnd:                source/_data/body-end.swig
        variable:                source/_data/variables.styl
        mixin:                   source/_data/mixins.styl
        style:                   source/_data/styles.styl