## configuration
# Site
title: Github Pages
subtitle:
description:
author: kdevkr
language: ko
timezone: UTC

# URL
url: kdevkr.github.io
root: /
permalink: archives/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
archive_dir: archives
category_dir: categories
i18n_dir: :lang
tag_dir: tags
skip_render: [README.md]

# Writing
default_layout: post
render_drafts: false
titlecase: true
external_link: true
post_asset_folder: true
future: false
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:
  theme: github-gist

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
date_format: YYYY-MM-DD
time_format: H:mm:ss

# Pagination
per_page: 10
pagination_dir: page

# Extendsions
theme: snorlax
deploy:
  type: git
  repo: https://__GITHUB_TOKEN__@github.com/kdevkr/kdevkr.github.io.git
  branch: master
menu:
  Home: /
  Archives: /archives
  Categories: /categories
  About: /about
google_analytics: UA-93954323-1
google_site_verification: googled619795c447b2a1d
naver_site_verification: 967670e7891eb52e115709ce4890e2e8f576a1e5
disqus_shortname: kdevkr-github-io

## plugins
index_generator:
  path: ''
  per_page: 10
  order_by: -date

category_generator:
  per_page: 10

archive_generator:
  per_page: 10
  yearly: true
  monthly: true
  daily: false
  order_by: -date

feed:
  type: atom
  path: atom.xml
  limit: false
  hub:
  content: true

article_emoji:
  full: true

browsersync:
  ui: false

# https://futurecreator.github.io/2016/06/23/search-engine-optimization-hexo-plugins/
nofollow:
    enable: true
